config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  devise_scope :user do
      get 'users/sign_out' => "devise/sessions#destroy"
  end

  scope "(:locale)", locale: /en|es|pt/  do
    get 'home/index'
    root 'pages#home'
    resources :articles
    resources :resources
    get 'pages/contact'
    get 'pages/home'
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :admin
      can :manage, :all
      can :dashboard, :all
      can :access, :rails_admin
    elsif user.has_role? :editor
      can :manage, :all
      can :dashboard, :all
      can :access, :rails_admin
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  translates :title, :text, :summary
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_one_attached :image

end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :logo

end

app/models/resource.rb
class Resource < ApplicationRecord
  translates :title, :description
  accepts_nested_attributes_for :translations, allow_destroy: true

  has_one_attached :attach
  has_one_attached :image

end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end

  def default_url_options
    { locale: I18n.locale }
  end
  
  private
    def set_locale
      I18n.locale = extract_locale || I18n.default_locale
    end

    def extract_locale
      parsed_locale = params[:locale] || request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/)[0] if request.env['HTTP_ACCEPT_LANGUAGE']
      I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
    end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def edit
  end

  def destroy
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def context
  end

  def contact
  end

  def home
  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @resources = Resource.all
  end

  def new
  end

  def edit
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<h1> <%= t('.title') %> </h1>

<% @articles.each do |article| %>
  <h2> <%= article.title %> </h2>
  <% if article.image.attached? %>
    <img src="<%= url_for(article.image) %>" alt="<%= article.image.filename %>">
  <% end %>
  <p> <%= article.summary %> </p>
  <%= link_to 'Show', article_path(article) %>
  <br>
<% end %>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>

<p><%= @article.created_at.strftime("%m/%d/%Y") %>

<h3> <%= @article.summary %> </h3>

<p> <%= @article.text %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alliance A</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit-icons.min.js"></script>


  </head>

  <body>

    <%= render 'shared/navbar' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/contact.html.erb
<h1> <%= t('.title') %> </h1>

app/views/pages/home.html.erb
<h1> <%= t('.title') %> </h1>

app/views/resources/index.html.erb
<h1> Resources </h1>

  <% @resources.each do |resource| %>
    <% if resource.image.attached? %>
      <img src="<%= url_for(resource.image) %>" alt="<%= resource.image.filename %>">
    <% end %>
    <h2> <%= resource.title %> </h2>
    <p> <%= resource.description %> </p>
    <% if resource.attach.attached? %>
      <%= link_to 'Descargar', url_for(resource.attach), target: "_blank" %>
    <% end %>
    <br>
  <% end %>

app/views/shared/_navbar.html.erb
<nav class="uk-navbar-container" uk-navbar>
  <div class="uk-navbar-left">

    <ul class="uk-navbar-nav">
      <li class="uk-active"> <%= link_to t('navbar.home'), root_path, :class => 'navbar-link'  %> </li>
      <li> <%= link_to t('navbar.contact'),  pages_contact_path , :class => 'navbar-link'  %> </li>
      <!-- <li>
        <a href="#"> Session </a>
        <div class="uk-navbar-dropdown">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <% if user_signed_in? %>
              <li> Logged in as <strong><%= current_user.email %></strong>. </li>
              <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
              <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>  </li>
              <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>  </li>
            <% end %>
          </ul>
        </div>
      </li> -->
      <li>
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= t('language_name') %>
        </a>
        <div class="uk-navbar-dropdown">
          <ul class="uk-nav uk-navbar-dropdown-nav">
            <li> <%= link_to t('language_name', locale: :en), request.params.merge(locale: :en), class: 'dropdown-item' %> </li>
            <li> <%= link_to t('language_name', locale: :es), request.params.merge(locale: :es), class: 'dropdown-item' %> </li>
            <li> <%= link_to t('language_name', locale: :pt), request.params.merge(locale: :pt), class: 'dropdown-item' %> </li>
          </ul>
        </div>
      </li>

    </ul>
  </div>
</nav>